BUGFIX: Adapt cache flushing to Neos 9 cache flushing
Flowpack/Flowpack.FullPageCache pull request #27
Opened 2024-12-30 12:45 UTC by dlubitz

Fixes #26

2024-12-31 13:28 UTC, mficzel requested changes
According to the composer.json the package still supports Neos 8.0 and 9.0. That is why we probably should intercept the following methods of the ContentCacheFlusher:

- `addTagToFlush` (with a deprecation notice for removal after 8.x support is dropped)
- `flushTagsImmediately`
- `collectTagsForFlushOnShutdown`

AFAIK the aspects react gracefully when a join point does not match so we still can support Neos 8 and 9 from a single version of FullPageCache.

2024-12-31 13:57 UTC, dlubitz commented
Hmm, but this will not work. The point in time when the tags are actually get flushed have changed. In Neos 8 it was always on shutdown. In Neos 9 its either immediate OR on shutdown.

If we do not match this, it could lead to unwanted cache entries (re-written cache with outdated data).

I would prefer to make it easy and make this version Neos 9 only. But we could make it downwards compatible by checking if the property "tagsToFlush" exists within the "onShutdown" aspect.

2025-01-02 13:06 UTC, mficzel commented
Looked again and the single aspect on `flushTagsImmediately` is totally fine for Neos 9 as this is called in `shutdownObject` aswell. So aspecting that single method also gets the timing right.

For Neos 8 i suggest to keep the code as previously implemented but use the `@Flow\Before("method(Neos\Neos\Fusion\Cache\ContentCacheFlusher->commit())")` instead of `@Flow\Before("method(Neos\Neos\Fusion\Cache\ContentCacheFlusher->shutdownObject())")` in the pointcut. That will never be triggered in Neos 9 and can be deprecated for removal once Neos 8 support is dropped.

2025-01-02 13:44 UTC, mficzel commented
Hmmm ...  if the ContentCacheFlusher would trigger a signal for the flushed tags we could get rid of the aspect entirely. That would make sense api wise as this is also needed by Varnish or CloudFlare adapters.

The last thing that would need a "proper" solution then would be the extraction of cache metadata that is currently done by the metadataAwareStringFrontend which does weird things to work around the fact that during reading we have no way to get the remaining lifetime and tags of a cache item.

2025-01-02 16:21 UTC, dlubitz commented
Yes, the signal would make sence, but would also be a breaking change and only work for 9.0, right?

2025-01-02 16:31 UTC, mficzel commented
yap ... and also it only makes sense with a way to get the needed metadata from the FusionContentCache in a clean way (Probably also via Signal) and not by adding a custom cache-frontend.

Probably way too late for 9.0 maybe we can introduce the needed apis in 9.1. 
For now i think we should keep this compatible with `~8.0 || ~9.0`

2025-01-02 17:05 UTC, dlubitz commented
Ok, I'll adapt this PR accordingly.

2025-01-03 13:26 UTC, dlubitz commented
@mficzel Done. Woul be great if you can test it with a Neos 8 instance.

2025-01-06 12:40 UTC, mficzel approved these changes
Looks fine and i can confirm that the tag-flushing still works in Neos 8 (tested 8.3)

2025-01-07 10:32 UTC, merged